name: On Release

on:
  push:
    branches:
    - beta-release
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: maven
    - name: Get version from POM
      id: pom-version
      uses: entimaniac/read-pom-version-action@1.0.0
    - name: Build
      run: mvn package
    - name: Upload to artifact
      uses: softprops/action-gh-release@v1
      with:
        files: target/zones-${{ steps.pom-version.outputs.version }}.jar
        tag_name: ${{ steps.pom-version.outputs.version }}
        body: 'This is a automatic build. Please visit our Ore page at "to be completed"'
        token: ${{secrets.GITHUB_TOKEN}}
        draft: false
        prerelease: true
        fail_on_unmatched_files: true
        
    
      
